language: java
install: true
jdk:
- openjdk8
jobs:
  include:
  - stage: test
    name: Build
    script: "./gradlew build --no-daemon"
  - stage: deploy
    name: Deploy Plugin
    if: |
      branch = master AND \
      type = push
    script:
    - ./gradlew publishPlugins --no-daemon -Pgradle.publish.key=${GRADLE_PUBLISH_KEY} -Pgradle.publish.secret=${GRADLE_PUBLISH_SECRET}
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"