# overriding default config from https://github.com/arturbosch/detekt/blob/master/detekt-core/src/main/resources/default-detekt-config.yml

build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    ignoreSimpleWhenEntries: true
    threshold: 11
  LongParameterList:
    functionThreshold: 12
    constructorThreshold: 12
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 20
    thresholdInObjects: 20
    thresholdInEnums: 20

performance:
  SpreadOperator:
    active: false

style:
  MaxLineLength:
    maxLineLength: 180
  ReturnCount:
    max: 3
  ThrowsCount:
    max: 3
