name: "Build branch"
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 8
          cache: "gradle"
      - name: Build
        run: ./gradlew build jacocoTestReport --no-daemon
